checksumBehavior: throw

defaultSemverRangePrefix: ""

enableHardenedMode: true

enableImmutableInstalls: true

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmRegistryServer: "https://registry.npmjs.org/"

unsafeHttpWhitelist: []

yarnPath: .yarn/releases/yarn-4.16.0.cjs
